version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 15
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - npm install
  build:
    commands:
      - echo "Building the web application..."
      - npm run build
    artifacts:
      files:
         - '**/*'
